# -*- coding: utf-8 -*-
"""Points7-8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ytO0wtlLGHcoPbeCFOrDGVk9JXSdd2QF

SETUP
"""

import os
import sys
import subprocess
import shutil


PROJECT_DIR = "MaskArchitectureAnomaly_CourseProject"
REPO_URL = "https://github.com/AlessandroMarinai/MaskArchitectureAnomaly_CourseProject.git"
EVAL_DIR = os.path.join(PROJECT_DIR, "eval")

ZIP_PATH = "./Anomaly_Validation_Datasets.zip"


# Clone the repository
try:
    subprocess.run(["git", "clone", REPO_URL], check=True)
except subprocess.CalledProcessError as e:
    print(f"Error cloning repository: {e}")
    sys.exit(1)

# Dependencies
dependencies = [
    "timm", "transformers", "accelerate", "panopticapi",
    "jsonargparse[signatures]", "lightning", "gitignore_parser"
]
try:
    # sys.executable ensures it uses the exact Python environment running this script
    subprocess.run([sys.executable, "-m", "pip", "install", "-q"] + dependencies, check=True)
except subprocess.CalledProcessError as e:
    print(f"Error installing dependencies: {e}")


# Extract the dataset
if os.path.exists(ZIP_PATH):
    os.makedirs(EVAL_DIR, exist_ok=True)

    # shutil.unpack_archive handles .zip, .tar, etc., natively in Python
    shutil.unpack_archive(ZIP_PATH, EVAL_DIR)
else:
    print(f"Dataset zip file not found at '{ZIP_PATH}'")

"""ERFNET"""

import os
import cv2
import glob
import torch
import random
from PIL import Image
import numpy as np
from erfnet import ERFNet
from argparse import ArgumentParser
from sklearn.metrics import average_precision_score, roc_curve
from torchvision.transforms import Compose, Resize, ToTensor

# Reproducibility
seed = 42
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)

n_classes = 20

# Improving GPU performance
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = True

# Image transformations:
input_transform = Compose([Resize((512, 1024), Image.BILINEAR), ToTensor()]) #Bilinear for RGB
target_transform = Compose([Resize((512, 1024), Image.NEAREST)]) #NN for discrete masks


# Metrics
def fpr_at_95_tpr(confidences, labels):
    """
    Calculates the False Positive Rate (FPR) when the
    True Positive Rate (TPR) is at exactly 95%.
    """
    fpr, tpr, thresholds = roc_curve(labels, confidences)
    idx = np.argmax(tpr >= 0.95)
    return fpr[idx]


def main():
    parser = ArgumentParser()
    parser.add_argument("--input", required=True, help="Glob pattern for input images.")

    parser.add_argument('--loadDir', default="/content/MaskArchitectureAnomaly_CourseProject/trained_models/")
    parser.add_argument('--loadWeights', default="erfnet_pretrained.pth")
    parser.add_argument('--method', default="maxlogit", choices=["maxlogit", "msp", "entropy"])
    args = parser.parse_args()

    # Initialization
    model = ERFNet(n_classes)
    model = torch.nn.DataParallel(model).cuda()

    weightspath = os.path.join(args.loadDir, args.loadWeights)

    # To handle models saved with or without DataParallel
    def load_my_state_dict(model, state_dict):
        state = model.state_dict()
        for name, param in state_dict.items():
            if name not in state:
                if name.startswith("module."):
                    state[name.split("module.")[-1]].copy_(param)
            else:
                state[name].copy_(param)
        return model

    # Load weights into the model and set to evaluation mode
    model = load_my_state_dict(model, torch.load(weightspath, map_location=lambda storage, loc: storage))
    model.eval()

    anomaly_score_list = []
    ood_gts_list = []


    # Scoring Loop
    for path in glob.glob(os.path.expanduser(args.input)):
        # Load transform and move the image to the GPU
        images = input_transform((Image.open(path).convert('RGB'))).unsqueeze(0).float().cuda()

        # Ensure channel dimension is correct
        images = images.permute(0,3,1,2) if images.shape[1] != 3 else images

        # Forward pass without calculating gradients
        with torch.no_grad():
            result = model(images)

        # Extract raw logits and move back to CPU
        logits = result.squeeze(0).cpu().numpy()

        # Calculate anomaly scores based on the chosen method
        if args.method == "maxlogit":
            # 1.0 minus the maximum logit across all classes
            anomaly_result = 1.0 - np.max(logits, axis=0)
        elif args.method == "msp":
            # Maximum Softmax Probability: 1.0 minus the highest confidence probability
            probs = torch.softmax(torch.from_numpy(logits), dim=0).numpy()
            anomaly_result = 1.0 - np.max(probs, axis=0)
        elif args.method == "entropy":
            # Normalized Predictive Entropy
            probs = torch.softmax(torch.from_numpy(logits), dim=0).numpy()
            entropy = -np.sum(probs * np.log(probs + 1e-10), axis=0)
            anomaly_result = entropy / np.log(n_classes)


        # Dynamically find the corresponding mask file based on the image path
        pathGT = path.replace("images", "labels_masks")
        if "RoadObsticle21" in pathGT: pathGT = pathGT.replace("webp", "png")
        if "fs_static" in pathGT: pathGT = pathGT.replace("jpg", "png")
        if "RoadAnomaly" in pathGT: pathGT = pathGT.replace("jpg", "png")

        mask = target_transform(Image.open(pathGT))
        ood_gts = np.array(mask)

        # Standardize mask values across different datasets:
        # 0 = Normal, 1 = Anomaly, 255 = Ignore
        if "RoadAnomaly" in pathGT:
            ood_gts = np.where((ood_gts==2), 1, ood_gts)

        if "LostAndFound" in pathGT:
            ood_gts = np.where((ood_gts==0), 255, ood_gts) # Ignore background
            ood_gts = np.where((ood_gts==1), 0, ood_gts)   # Normal
            ood_gts = np.where((ood_gts>1)&(ood_gts<201), 1, ood_gts) # Anomalies

        # Skip images that do not contain any actual anomalies (class 1)
        if 1 not in np.unique(ood_gts): continue

        # Store results for final metric calculation
        ood_gts_list.append(ood_gts)
        anomaly_score_list.append(anomaly_result)

        # Free up GPU memory
        torch.cuda.empty_cache()

    #Final Metric Calculation

    # Abort if no valid ground truth images were processed
    if len(ood_gts_list) == 0:
        return

    # Convert lists to numpy arrays
    ood_gts = np.array(ood_gts_list)
    anomaly_scores = np.array(anomaly_score_list)

    # Create boolean masks to separate normal (ind) and anomalous (ood) pixels
    ood_mask = (ood_gts == 1)
    ind_mask = (ood_gts == 0)

    # Flatten and concatenate the scores and labels into 1D arrays
    val_out = np.concatenate((anomaly_scores[ind_mask], anomaly_scores[ood_mask]))
    val_label = np.concatenate((np.zeros(np.sum(ind_mask)), np.ones(np.sum(ood_mask))))

    # Calculate the area under the PR Curve and FPR at 95% TPR
    prc_auc = average_precision_score(val_label, val_out)
    fpr = fpr_at_95_tpr(val_out, val_label)

    print(f'AUPRC score: {prc_auc*100.0:.2f}%')
    print(f'FPR@TPR95: {fpr*100.0:.2f}%')

if __name__ == '__main__':
    main()

import os
import subprocess
import sys

datasets = ["RoadAnomaly21", "RoadObsticle21", "FS_LostFound_full", "fs_static", "RoadAnomaly"]
methods = ["maxlogit", "msp", "entropy"]


eval_dir = os.path.join(".", "eval")

try:
    os.chdir(eval_dir)
except FileNotFoundError:
    print(f"Error: Directory '{eval_dir}' not found.")
    sys.exit(1)


for dataset in datasets:
    print(f"\n\n{'='*40}\n>>> DATASET: {dataset} <<<\n{'='*40}")

    for method in methods:
        print(f"\n--- Method: {method.upper()} ---")

        # Define the relative path to the images for this specific dataset
        input_path = f"Validation_Dataset/{dataset}/images/*.*"

        # Construct the terminal command as a list of strings
        command = [
            sys.executable,
            "run_erfnet_anomaly.py",
            "--input", input_path,
            "--method", method
        ]

        # Execute the command
        try:
            # check=True ensures the script stops and throws an error if the subprocess fails
            subprocess.run(command, check=True)
        except subprocess.CalledProcessError as e:
            print(f"\n[!] Error running evaluation for {dataset} with {method}.")
            print(f"Details: {e}")
            sys.exit(1)

"""EOMT"""

import os
import glob
import torch
import torch.nn.functional as F
from torch.amp.autocast_mode import autocast
import random
from PIL import Image
import numpy as np
from argparse import ArgumentParser
from sklearn.metrics import average_precision_score, roc_curve
from torchvision.transforms import Compose, Resize, ToTensor
import yaml
import importlib
import sys
import math


sys.path.insert(0, '/content/MaskArchitectureAnomaly_CourseProject/eomt')

seed = 42
random.seed(seed)
np.random.seed(seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = True

# Target masks use NEAREST interpolation to preserve exact integer class labels
target_transform = Compose([Resize((512, 1024), Image.NEAREST)])

# Metrics
def fpr_at_95_tpr(confidences, labels):
    """Calculates False Positive Rate at exactly 95% True Positive Rate."""
    fpr, tpr, thresholds = roc_curve(labels, confidences)
    idx = np.argmax(tpr >= 0.95)
    return fpr[idx]

# Model initialization
def load_eomt_model(config_path, ckpt_path, device):
    with open(config_path) as f:
        config = yaml.safe_load(f)

    # Load weights to CPU first
    state_dict = torch.load(ckpt_path, map_location='cpu', weights_only=True)
    if "state_dict" in state_dict:
        state_dict = state_dict["state_dict"]

    # Dynamic image size fix
    img_size = [640, 640]
    for k, v in state_dict.items():
        if 'pos_embed' in k and len(v.shape) == 3:
            num_patches = v.shape[1]
            grid_size = int(math.sqrt(num_patches))
            img_size = [grid_size * 16, grid_size * 16]
            break

    data_args = config.get("data", {}).get("init_args", {})
    num_classes = data_args.get("num_classes", 19)

    # Dynamically import the Encoder class from the config
    enc_cfg = config["model"]["init_args"]["network"]["init_args"]["encoder"]
    enc_cls = getattr(importlib.import_module(enc_cfg["class_path"].rsplit(".", 1)[0]), enc_cfg["class_path"].rsplit(".", 1)[1])
    encoder = enc_cls(img_size=img_size, **enc_cfg.get("init_args", {}))

    # Dynamically import the Network class
    net_cfg = config["model"]["init_args"]["network"]
    net_cls = getattr(importlib.import_module(net_cfg["class_path"].rsplit(".", 1)[0]), net_cfg["class_path"].rsplit(".", 1)[1])
    net_kwargs = {k: v for k, v in net_cfg["init_args"].items() if k != "encoder"}
    network = net_cls(masked_attn_enabled=False, num_classes=num_classes, encoder=encoder, **net_kwargs)

    # Dynamically import the Lightning Module
    lit_cfg = config["model"]
    lit_cls = getattr(importlib.import_module(lit_cfg["class_path"].rsplit(".", 1)[0]), lit_cfg["class_path"].rsplit(".", 1)[1])
    model_kwargs = {k: v for k, v in config["model"]["init_args"].items() if k != "network"}

    if "stuff_classes" in data_args:
        model_kwargs["stuff_classes"] = data_args["stuff_classes"]


    model = lit_cls(img_size=img_size, num_classes=num_classes, network=network, **model_kwargs).eval().to(device)
    model.load_state_dict(state_dict, strict=False)

    return model, num_classes

@torch.no_grad()
def infer_semantic(model, img, device):
    """Runs a forward pass through the EOMT model using Mixed Precision."""
    imgs = [img.to(device)]
    img_sizes = [img.shape[-2:] for img in imgs]

    # Dynamically set precision based on hardware capabilities
    device_type = 'cuda' if device.type == 'cuda' else 'cpu'
    dtype = torch.float16 if device_type == 'cuda' else torch.bfloat16


    with autocast(device_type=device_type, dtype=dtype):
        # Model uses a sliding window/crop approach
        if hasattr(model, 'window_imgs_semantic'):
            crops, origins = model.window_imgs_semantic(imgs)
            mask_logits_per_layer, class_logits_per_layer = model(crops)

            mask_logits = F.interpolate(mask_logits_per_layer[-1], model.img_size, mode="bilinear")
            crop_logits = model.to_per_pixel_logits_semantic(mask_logits, class_logits_per_layer[-1])
            logits = model.revert_window_logits_semantic(crop_logits, origins, img_sizes)

        # Model uses standard resizing/padding
        else:
            transformed_imgs = model.resize_and_pad_imgs_instance_panoptic(imgs)
            mask_logits_per_layer, class_logits_per_layer = model(transformed_imgs)

            mask_logits = F.interpolate(mask_logits_per_layer[-1], model.img_size, mode="bilinear")
            prob_masks = mask_logits.sigmoid()
            prob_classes = class_logits_per_layer[-1].softmax(dim=-1)[..., :-1]

            # Combine mask predictions with class probabilities
            semantic_logits = torch.einsum("bqc,bqhw->bchw", prob_classes, prob_masks)
            logits = model.revert_resize_and_pad_logits_instance_panoptic(semantic_logits, img_sizes)

    # Return to CPU as float32 for metric calculation
    return logits[0].float().cpu()


def main():
    parser = ArgumentParser()
    parser.add_argument("--input", required=True, help="Glob pattern for images")
    parser.add_argument('--config', required=True, help="Path to model config YAML")
    parser.add_argument('--ckpt', required=True, help="Path to model checkpoint")
    parser.add_argument('--method', default="maxlogit", choices=["maxlogit", "msp", "entropy", "rba"])
    args = parser.parse_args()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model, num_classes = load_eomt_model(args.config, args.ckpt, device)

    anomaly_score_list = []
    ood_gts_list = []

    # Iterate through all images matching the input pattern
    for path in glob.glob(os.path.expanduser(args.input)):
        img = Image.open(path).convert('RGB')
        img = img.resize((1024, 512), Image.BILINEAR)

        # Keep as raw bytes tensor instead of ToTensor() float mapping
        img_t = torch.from_numpy(np.array(img)).permute(2, 0, 1)

        logits = infer_semantic(model, img_t, device).numpy()

        # Apply the selected anomaly scoring function
        if args.method == "maxlogit":
            anomaly_result = 1.0 - np.max(logits, axis=0)
        elif args.method == "msp" or args.method == "rba":
            probs = torch.softmax(torch.from_numpy(logits), dim=0).numpy()
            anomaly_result = 1.0 - np.max(probs, axis=0)
        elif args.method == "entropy":
            probs = torch.softmax(torch.from_numpy(logits), dim=0).numpy()
            entropy = -np.sum(probs * np.log(probs + 1e-10), axis=0)
            anomaly_result = entropy / np.log(num_classes)

        # Processing
        pathGT = path.replace("images", "labels_masks")
        if "RoadObsticle21" in pathGT: pathGT = pathGT.replace("webp", "png")
        if "fs_static" in pathGT: pathGT = pathGT.replace("jpg", "png")
        if "RoadAnomaly" in pathGT: pathGT = pathGT.replace("jpg", "png")

        mask = target_transform(Image.open(pathGT))
        ood_gts = np.array(mask)

        # Standardize mask values: 0 = Normal, 1 = Anomaly, 255 = Ignore
        if "RoadAnomaly" in pathGT:
            ood_gts = np.where((ood_gts==2), 1, ood_gts)

        if "LostAndFound" in pathGT:
            ood_gts = np.where((ood_gts==0), 255, ood_gts)
            ood_gts = np.where((ood_gts==1), 0, ood_gts)
            ood_gts = np.where((ood_gts>1)&(ood_gts<201), 1, ood_gts)

        # Skip images without anomalies
        if 1 not in np.unique(ood_gts): continue

        ood_gts_list.append(ood_gts)
        anomaly_score_list.append(anomaly_result)

    # Metric calculation
    if len(ood_gts_list) == 0:
        return

    ood_gts = np.array(ood_gts_list)
    anomaly_scores = np.array(anomaly_score_list)

    ood_mask = (ood_gts == 1)
    ind_mask = (ood_gts == 0)

    # Flatten predictions and ground truths for Scikit-Learn
    val_out = np.concatenate((anomaly_scores[ind_mask], anomaly_scores[ood_mask]))
    val_label = np.concatenate((np.zeros(np.sum(ind_mask)), np.ones(np.sum(ood_mask))))

    prc_auc = average_precision_score(val_label, val_out)
    fpr = fpr_at_95_tpr(val_out, val_label)

    print(f'AUPRC score: {prc_auc*100.0:.2f}%')
    print(f'FPR@TPR95: {fpr*100.0:.2f}%')

if __name__ == '__main__':
    main()

import os
import subprocess
import sys

datasets = ["RoadAnomaly21", "RoadObsticle21", "FS_LostFound_full", "fs_static", "RoadAnomaly"]
methods = ["maxlogit", "msp", "entropy", "rba"]

CONFIG_PATH = "../eomt/configs/dinov2/cityscapes/semantic/eomt_base_640.yaml"

CHECKPOINT_PATH = "../weights/eomt_cityscapes.bin"

eval_dir = os.path.join(".", "eval")

try:
    os.chdir(eval_dir)
except FileNotFoundError:
    print(f"Error: Directory '{eval_dir}' not found.")
    sys.exit(1)

for dataset in datasets:
    print(f"\n\n{'='*40}\n>>> DATASET: {dataset} <<<\n{'='*40}")

    for method in methods:
        print(f"\n--- Method: {method.upper()} ---")

        # Define the relative path to the images for this specific dataset
        input_path = f"Validation_Dataset/{dataset}/images/*.*"

        command = [
            sys.executable,
            "run_eomt_anomaly.py",
            "--input", input_path,
            "--config", CONFIG_PATH,
            "--ckpt", CHECKPOINT_PATH,
            "--method", method
        ]

        # Execute the command
        try:
            # check=True ensures the script throws an error if the subprocess fails
            subprocess.run(command, check=True)
        except subprocess.CalledProcessError as e:
            print(f"\n[!] Error running evaluation for {dataset} with {method}.")
            print(f"Details: {e}")
            sys.exit(1)

"""Temperature Scaling"""

import os
import glob
import torch
import numpy as np
from PIL import Image
from argparse import ArgumentParser
from erfnet import ERFNet
from sklearn.metrics import average_precision_score, roc_curve
from torchvision.transforms import Compose, Resize, ToTensor


n_classes = 20

# Bilinear interpolation for the RGB images, Nearest Neighbor for the integer masks
input_transform = Compose([Resize((512, 1024), Image.BILINEAR), ToTensor()])
target_transform = Compose([Resize((512, 1024), Image.NEAREST)])

def fpr_at_95_tpr(confidences, labels):
    """Calculates the False Positive Rate when the True Positive Rate hits 95%."""
    fpr, tpr, _ = roc_curve(labels, confidences)
    idx = np.argmax(tpr >= 0.95)
    return fpr[idx]

def main():

    parser = ArgumentParser()
    parser.add_argument("--input", required=True, help="Glob pattern for input images.")


    parser.add_argument('--loadWeights', default="./trained_models/erfnet_pretrained.pth")
    args = parser.parse_args()

    model = ERFNet(n_classes)
    model = torch.nn.DataParallel(model).cuda()

    state_dict = torch.load(args.loadWeights, map_location='cpu', weights_only=True)
    own_state = model.state_dict()
    for name, param in state_dict.items():
        if name not in own_state:
            if name.startswith("module."):
                own_state[name.split("module.")[-1]].copy_(param)
        else:
            own_state[name].copy_(param)

    # Set model to evaluation mode
    model.eval()

    # Setup
    # Define the temperatures to test. T=1.0 is the standard baseline.
    temperatures = [0.5, 0.75, 1.0, 1.1, 1.5, 2.0]

    # Dictionary to hold the anomaly scores for every temperature setting
    anomaly_scores = {t: [] for t in temperatures}
    ood_gts_list = []


    for path in glob.glob(os.path.expanduser(args.input)):
        # Load and transform image
        images = input_transform((Image.open(path).convert('RGB'))).unsqueeze(0).float().cuda()
        images = images.permute(0,3,1,2) if images.shape[1] != 3 else images

        with torch.no_grad():
            result = model(images)

        # Extract raw unnormalized logits
        logits = result.squeeze(0)

        # Apply temperature scaling: Divide logits by T before calculating Softmax
        for t in temperatures:
            scaled_logits = logits / t
            probs = torch.softmax(scaled_logits, dim=0).cpu().numpy()

            # Anomaly score is 1.0 minus the highest confidence class probability
            anomaly_score = 1.0 - np.max(probs, axis=0)
            anomaly_scores[t].append(anomaly_score)

        # Processing
        pathGT = path.replace("images", "labels_masks")
        if "RoadObsticle21" in pathGT: pathGT = pathGT.replace("webp", "png")
        if "fs_static" in pathGT: pathGT = pathGT.replace("jpg", "png")
        if "RoadAnomaly" in pathGT: pathGT = pathGT.replace("jpg", "png")

        mask = target_transform(Image.open(pathGT))
        ood_gts = np.array(mask)

        # Standardize labels: 0 = Normal, 1 = Anomaly, 255 = Ignore
        if "RoadAnomaly" in pathGT:
            ood_gts = np.where((ood_gts==2), 1, ood_gts)

        if "LostAndFound" in pathGT:
            ood_gts = np.where((ood_gts==0), 255, ood_gts)
            ood_gts = np.where((ood_gts==1), 0, ood_gts)
            ood_gts = np.where((ood_gts>1)&(ood_gts<201), 1, ood_gts)

        # If the image has no valid anomalies, remove the appended scores for this image across all temperatures to keep arrays aligned
        if 1 not in np.unique(ood_gts):
            for t in temperatures:
                anomaly_scores[t].pop()
            continue

        ood_gts_list.append(ood_gts)
        torch.cuda.empty_cache()

    if len(ood_gts_list) == 0:
        print("No valid Ground Truth found for this dataset.")
        return

    ood_gts_arr = np.array(ood_gts_list)
    ood_mask = (ood_gts_arr == 1)
    ind_mask = (ood_gts_arr == 0)

    # Create the flattened true label array
    val_label = np.concatenate((np.zeros(np.sum(ind_mask)), np.ones(np.sum(ood_mask))))

    # Evaluate metrics for each temperature setting independently
    for t in temperatures:
        scores_arr = np.array(anomaly_scores[t])

        # Flatten predictions
        val_out = np.concatenate((scores_arr[ind_mask], scores_arr[ood_mask]))

        prc_auc = average_precision_score(val_label, val_out)
        fpr = fpr_at_95_tpr(val_out, val_label)

        print(f"T={t:<4} | AUPRC: {prc_auc*100.0:.2f}% | FPR@TPR95: {fpr*100.0:.2f}%")

if __name__ == '__main__':
    main()

import os
import subprocess
import sys

datasets = ["RoadAnomaly21", "RoadObsticle21", "FS_LostFound_full", "fs_static", "RoadAnomaly"]


eval_dir = os.path.join(".", "eval")

try:
    os.chdir(eval_dir)
except FileNotFoundError:
    print(f"Error: Directory '{eval_dir}' not found.")
    sys.exit(1)


for dataset in datasets:
    print(f"\n\n{'='*40}\n>>> DATASET: {dataset} <<<\n{'='*40}")

    input_path = f"Validation_Dataset/{dataset}/images/*.*"

    # Construct the terminal command as a list of strings
    command = [
        sys.executable,
        "run_temp_scaling.py",
        "--input", input_path
    ]

    # Execute the command
    try:
        subprocess.run(command, check=True)
    except subprocess.CalledProcessError as e:
        print(f"\n[!] Error running temperature scaling evaluation for {dataset}.")
        print(f"Details: {e}")